name: Integration Tests

on:
  push:
    branches:
      - master
      - it/**

jobs:


  go-integration-tests:
    name: Go Integration Tests

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get commit id
        id: commitId
        run: echo "::set-output name=commitId::$(git log --format=%H -n 1)"
      - name: update status
        run: |
          curl --location --request POST 'https://api.github.com/repos/SAP/jenkins-library/statuses/${{ steps.commitId.outputs.commitId }}' -H 'Content-Type: application/json' --data '{"state": "pending", "context": "Go / integration-tests", "target_url": "https://github.com/SAP/jenkins-library/actions/runs/${{ github.run_id }}"}' -H 'Authorization: token ${{secrets.INTEGRATION_TEST_VOTING_TOKEN}}'
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: build
        env:
          CGO_ENABLED: 0
      # with `-tags release` we ensure that shared test utilities won't end up in the binary
        run: go build -o piper -tags release
      - name: test
        env:
          PIPER_INTEGRATION_GITHUB_TOKEN: ${{secrets.PIPER_INTEGRATION_GITHUB_TOKEN}}
        run: go test -tags=integration -timeout 20m ./integration/...
      - name: update status
        if: success()
        run: |
          curl --location --request POST 'https://api.github.com/repos/SAP/jenkins-library/statuses/${{ steps.commitId.outputs.commitId }}' -H 'Content-Type: application/json' --data '{"state": "success", "context": "Go / integration-tests", "target_url": "https://github.com/SAP/jenkins-library/actions/runs/${{ github.run_id }}"}' -H 'Authorization: token ${{secrets.INTEGRATION_TEST_VOTING_TOKEN}}'
      - name: update status
        if: cancelled() || failure()
        run: |
          curl --location --request POST 'https://api.github.com/repos/SAP/jenkins-library/statuses/${{ steps.commitId.outputs.commitId }}' -H 'Content-Type: application/json' --data '{"state": "failure", "context": "Go / integration-tests", "target_url": "https://github.com/SAP/jenkins-library/actions/runs/${{ github.run_id }}"}' -H 'Authorization: token ${{secrets.INTEGRATION_TEST_VOTING_TOKEN}}'
